# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-06-21 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_for_users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('fans', models.ManyToManyField(related_name='favorite_books', to='app_for_users.User')),
            ],
        ),
    ]
